config/routes.rb
Rails.application.routes.draw do
  root 'facts#index'

  resources :facts

  devise_for :users

  devise_scope :user do
    get 'users/sign_up' => 'registrations#new'
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :fact
  belongs_to :user
end

app/models/evidence.rb
class Evidence < ActiveRecord::Base
  belongs_to :user
  belongs_to :fact
  has_many :votes

  def upvotes
    votes.where(upvote: true).count
  end

  def downvotes
    votes.where(upvote: false).count
  end
end

app/models/fact.rb
class Fact < ActiveRecord::Base
  belongs_to :user
  has_many :evidences

  accepts_nested_attributes_for :evidences, reject_if: :all_blank, allow_destroy: true

  def supporting_evidence
    evidences.where(support: true)
  end

  def refuting_evidence
    evidences.where(support: false)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :facts
  has_many :comments
  has_many :evidences
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :evidence
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  before_action :load_fact, only: [:show, :edit, :update, :destroy]

  def index
    @facts = Fact.all
  end

  def new
    @fact = Fact.new
  end

  def show
    @fact = Fact.find(params[:id])
  end

  def create
    @fact = Fact.create(fact_params)

    @fact.user = current_user
    if @fact.save
      redirect_to fact_path(@fact), notice: 'Fact successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @fact.update_attributes(fact_params)
    if @fact.save
      redirect_to fact_path(@fact), notice: 'Fact successfully created.'
    else
      render :edit
    end
  end

  def destroy
    @fact.destroy
    redirect_to facts_url notice: 'Fact Successfully Deleted'
  end

  private

  def fact_params
    params.require(:fact).permit(:body, :user_id,
                                 evidences_attributes: [:url, :support])
  end

  def load_fact
    @fact = Fact.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :display_name)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :display_name, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/facts/_evidence_fields.html.erb
<div class="nested-fields">

  <div >
    <%= f.label :url %>
    <%= f.url_field :url %>
  </div>
  <div >
    <%= f.label :support, "Supporting" %>
    <%= f.radio_button :support, true, value: true, checked: false %>
    <%= f.label :support, "Refuting" %>
    <%= f.radio_button :support, false, value: false, checked: false %>
  </div>

  <%= link_to_remove_association "Remove Evidence", f %>
</div>

app/views/facts/_form.html.erb
<%= form_for @fact do |f| %>
    <div class="field">
      <%= f.label :body %><br/>
      <%= f.text_area :body, autofocus: true %>
    </div>

    <div id="evidences">
      <%= f.fields_for :evidences do |evidence_fields| %>
        <%= render 'evidence_fields', f: evidence_fields %>
      <% end %>

      <div class="links">
        <%= link_to_add_association "Add Evidence", f, :evidences %>
      </div>
    </div>

    <div>
      <%= f.submit %>
    </div>
<% end %>

app/views/facts/edit.html.erb
<h1>Edit Fact</h1>
<%= render 'form' %>

app/views/facts/index.html.erb
<h1>All Facts</h1>
<div class="facts-container">
  <ul>
    <% @facts.each do |fact| %>
    <li>
      <p><%= link_to fact.body, fact_path(fact) %></p>
    </li>
    <% end %>
  </ul>
</div>

app/views/facts/new.html.erb
<h1>New Fact</h1>
<%= render 'form' %>

app/views/facts/show.html.erb
<h1>Facts#show</h1>

<div>
  <p>
    <strong><%= User.find(@fact.user_id).display_name %></strong> posted this fact!
  </p>

  <p>
    <%= @fact.body %>
  </p>
</div>

<div>
  <h2><%= pluralize @fact.supporting_evidence.count, 'piece' %> of supporting evidence:</h2>
  <ul>
    <% @fact.supporting_evidence.each do |evidence| %>
      <li>
        <h4><%= evidence.url%></h4>
        <p>Posted by <%= evidence.user.display_name %></p>
        <p><%= "#{pluralize evidence.upvotes, 'upvote'} | #{pluralize evidence.downvotes, 'downvote'}" %></p>
      </li>
    <% end %>
  </ul>
</div>

<div>
  <h2><%= pluralize @fact.refuting_evidence.count, 'piece' %> of refuting evidence:</h2>
  <ul>
    <% @fact.refuting_evidence.each do |evidence| %>
      <li>
        <h4><%= evidence.url%></h4>
        <p>Posted by <%= evidence.user.display_name %></p>
        <p><%= "#{pluralize evidence.upvotes, 'upvote'} | #{pluralize evidence.downvotes, 'downvote'}" %></p>
      </li>
    <% end %>
  </ul>
</div>

<% if current_user == User.find(@fact.user_id)  %>
  <%= link_to "Delete Fact", fact_path(@fact), method: :delete, date: {confirm:"Are you sure you want to delete this
  fact?"} %>
<% end  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TruthyFalsey</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="flash-notifications">
  <p id="alert"><%= flash[:alert] %></p>
  <p id="alert"><%= flash[:notice] %></p>
</div>

<div>
  <% if user_signed_in? %>
      <p><%= link_to "Facts Index", facts_path %> | <%= link_to "New Fact", new_fact_path %></p>
      <p><%= link_to('Logout', destroy_user_session_path, :method => :delete)%></p>
  <% else %>
      <p><%= link_to "Facts Index", facts_path %> | <%= link_to "New Fact", new_user_session_url %></p>
      <p><%= link_to('Login', new_user_session_path)%></p>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>